[project]
name = "demo_project_1"
version = "0.1.0"
description = "demo_project-1 using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.175.0,<1.0.0"
]

[project.scripts]
demo_project_1 = "demo_project_1.main:run"
run_crew = "demo_project_1.main:run"
train = "demo_project_1.main:train"
replay = "demo_project_1.main:replay"
test = "demo_project_1.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
